pipeline {
    agent any
    stages {
        stage('build project1 microservice') {
            steps {
                echo 'Executing project1 microservice pipeline commands...' 
            }
        }
    }
}