pipeline {
    agent any
    stages {
        stage('build project2 microservice') {
            steps {
                echo 'Executing project2 microservice pipeline commands...' 
            }
        }
    }
}