pipeline {
    agent any
    stages {
        stage('build project2 microfrontend') {
            steps {
                echo 'Executing project2 microfrontend pipeline commands...' 
            }
        }
    }
}