pipeline {
    agent any
    stages {
        stage('build project1 microfrontend') {
            steps {
                echo 'Executing project1 microfrontend pipeline commands...' 
            }
        }
    }
}